language: node_js
sudo: required
node_js:
  - "6.9.0"

before_script:
  - npm install -g codeclimate-test-reporter
  - scripts/quickstart.sh
  - npm install

script:
  - npm run coverage

after_success:
  codeclimate-test-reporter < coverage/lcov.info
